import type { Exercise } from "./types";

const createdAt = "2026-07-17T00:00:00.000Z";

export const builtinExercises: Exercise[] = [
  {
    id: "builtin-ki-arbeitswelt",
    title: "Wenn Maschinen mitentscheiden",
    subtitle: "Wie künstliche Intelligenz Arbeit verändert, ohne den Menschen einfach überflüssig zu machen.",
    topic: "Arbeitswelt & KI",
    level: "C1",
    estimatedMinutes: 9,
    createdAt,
    paragraphs: [
      "Kaum eine Debatte über die Zukunft der Arbeit kommt derzeit ohne dramatische Prognosen aus. Während die einen eine neue Ära der Produktivität erwarten, warnen andere vor massenhafter Erwerbslosigkeit. Beide Perspektiven behandeln künstliche Intelligenz häufig wie eine eigenständig handelnde Kraft, die von außen über Betriebe hereinbricht. Tatsächlich hängt ihre Wirkung jedoch davon ab, für welche Aufgaben Unternehmen sie einsetzen, wie Arbeitsprozesse organisiert werden und wer über die gewonnenen Daten verfügt. Technik ersetzt deshalb nicht einfach Berufe; sie verändert zunächst die Verteilung einzelner Tätigkeiten innerhalb eines Berufs.",
      "Das lässt sich in Verwaltungen beobachten. Systeme können Anträge vorsortieren, wiederkehrende Angaben prüfen und Formulierungen vorschlagen. Dadurch entfällt ein Teil monotoner Routinearbeit. Gleichzeitig wächst die Verantwortung der Beschäftigten: Sie müssen erkennen, wann ein automatisch erzeugter Vorschlag unplausibel ist, und ihre Entscheidung gegenüber Bürgerinnen und Bürgern begründen. Wer die Technik lediglich bedient, ohne ihre Grenzen zu verstehen, kann Fehler schneller vervielfältigen als zuvor. Automatisierung schafft hier also nicht nur Entlastung, sondern auch neue Anforderungen an Urteilskraft und Fachwissen.",
      "Ähnlich ambivalent ist die Entwicklung in kreativen Berufen. Übersetzerinnen, Designer und Redakteurinnen nutzen generative Programme bereits für erste Entwürfe. Das beschleunigt manche Arbeitsschritte, kann aber den wirtschaftlichen Wert einfacher Aufträge senken. Besonders Berufseinsteiger geraten unter Druck, weil gerade jene kleineren Aufgaben verschwinden könnten, an denen sie früher Erfahrung sammelten. Wenn Unternehmen nur noch erfahrene Fachkräfte beschäftigen, fehlt langfristig der Nachwuchs. Die kurzfristige Einsparung würde dann zu einem strukturellen Qualifikationsproblem führen.",
      "Ob Beschäftigte von der neuen Produktivität profitieren, ist zudem eine Verteilungsfrage. Ein Unternehmen kann Zeitgewinne nutzen, um Arbeitszeiten zu verkürzen, Dienstleistungen zu verbessern oder höhere Gewinne zu erzielen. Welche Variante gewählt wird, entscheidet keine Software. In Betrieben mit starker Mitbestimmung werden Einführung, Leistungsüberwachung und Weiterbildungsbedarf eher gemeinsam geregelt. Wo solche Verfahren fehlen, erleben Beschäftigte dieselbe Technologie möglicherweise vor allem als Instrument verdichteter Arbeit und permanenter Kontrolle.",
      "Hinzu kommt das Problem der Messbarkeit. Digitale Systeme erfassen leicht, wie viele Vorgänge jemand bearbeitet oder wie schnell eine Antwort erfolgt. Schwerer messbar sind geduldige Beratung, kollegiale Unterstützung und die Fähigkeit, einen ungewöhnlichen Fall frühzeitig zu erkennen. Wenn nur quantifizierbare Leistungen zählen, passen Menschen ihr Verhalten an die Kennzahlen an. Die Organisation wird auf dem Papier effizienter, während die Qualität ihrer Arbeit unbemerkt sinken kann. Fachleute sprechen deshalb von einem Steuerungsproblem und nicht bloß von einem technischen Problem.",
      "Für Bildungspolitik folgt daraus, dass Weiterbildung mehr sein muss als eine kurze Programmeinweisung. Beschäftigte benötigen Grundkenntnisse über Daten, Wahrscheinlichkeiten und systematische Verzerrungen, zugleich aber auch Gelegenheit, ihr berufliches Erfahrungswissen weiterzuentwickeln. Nicht alle müssen programmieren können. Entscheidend ist, fachlich begründet widersprechen zu können, wenn ein System einen fragwürdigen Vorschlag macht. Solche Kompetenzen entstehen nicht unter ständigem Zeitdruck, sondern durch Erprobung, Austausch und eine Fehlerkultur, die Unsicherheit zulässt.",
      "Auch bei der Personalauswahl ist Vorsicht geboten. Lernende Systeme können frühere Einstellungsentscheidungen auswerten und daraus vermeintlich erfolgreiche Profile ableiten. Waren bestimmte Gruppen in der Vergangenheit benachteiligt, erscheint diese Ungleichheit in den Daten als normales Muster. Ein formal neutrales Verfahren kann sie anschließend fortschreiben. Transparenz bedeutet deshalb nicht nur, den mathematischen Aufbau zu veröffentlichen. Bewerberinnen und Bewerber brauchen verständliche Kriterien, eine menschliche Ansprechperson und eine wirksame Möglichkeit, Entscheidungen anzufechten.",
      "Kleine Unternehmen stehen vor einer anderen Herausforderung. Sie verfügen selten über eigene Fachabteilungen, kaufen aber zunehmend fertige Anwendungen ein. Damit geben sie einen Teil ihrer Kontrolle an externe Anbieter ab. Ändert ein Dienst seine Preise, Datenschutzregeln oder Funktionen, lässt sich der Arbeitsprozess nicht immer kurzfristig umstellen. Öffentliche Beratungsangebote und gemeinsame Branchenstandards könnten verhindern, dass verantwortlicher Technikeinsatz zu einem Privileg großer Konzerne wird.",
      "Schließlich verändert KI die Vorstellung davon, was als gute Arbeit gilt. Wenn ein Programm in Sekunden einen brauchbaren Standardtext erzeugt, gewinnt nicht zwangsläufig das schnellste Ergebnis an Wert. Wichtiger können sorgfältige Auswahl, Kontextwissen und die Fähigkeit werden, unterschiedliche Interessen zu erkennen. Das setzt allerdings voraus, dass Auftraggeber Qualität honorieren und nicht jede Zeitersparnis unmittelbar in zusätzliche Aufgaben umwandeln. Produktivität ist nur dann ein Fortschritt, wenn sie auch Handlungsspielräume erweitert.",
      "Die sinnvollste Frage lautet daher nicht, welche Berufe verschwinden werden. Produktiver ist die Frage, welche Tätigkeiten Menschen abgeben möchten, welche Entscheidungen menschlicher Verantwortung vorbehalten bleiben und wie die Vorteile verteilt werden. Künstliche Intelligenz kann Arbeit erleichtern, doch sie kann ebenso bestehende Ungleichheiten verschärfen. Ihre gesellschaftliche Bilanz steht nicht im Programmcode fest. Sie entsteht in Tarifverhandlungen, Unternehmensentscheidungen, Gesetzen und im alltäglichen Umgang mit den Systemen.",
    ],
    mcq: [
      { question: "Welche Hauptthese vertritt der Text?", options: ["KI ersetzt kurzfristig fast alle Berufe.", "Die Wirkung von KI wird wesentlich durch organisatorische und politische Entscheidungen bestimmt.", "Nur Programmierer können KI-Systeme verantwortungsvoll nutzen.", "Kreative Berufe bleiben von Automatisierung unberührt."], correctIndex: 1, explanation: "Der Text betont durchgehend, dass Einsatzform, Mitbestimmung, Bildung und Verteilung über die Folgen entscheiden." },
      { question: "Warum könnten wegfallende Einstiegsaufgaben langfristig problematisch sein?", options: ["Weil erfahrene Beschäftigte keine Software bedienen können.", "Weil Unternehmen dann mehr Praktikanten einstellen müssen.", "Weil Nachwuchskräfte weniger Möglichkeiten haben, berufliche Erfahrung aufzubauen.", "Weil kreative Arbeit gesetzlich nicht automatisiert werden darf."], correctIndex: 2, explanation: "Einfache Aufträge dienten Berufseinsteigern bisher als Lern- und Erfahrungsraum." },
      { question: "Welche Gefahr verbindet der Text mit Kennzahlen?", options: ["Sie machen digitale Arbeit grundsätzlich unmöglich.", "Messbare Geschwindigkeit kann wichtiger werden als schwer messbare Qualität.", "Sie verhindern jede Form der Leistungsbewertung.", "Sie führen automatisch zu kürzeren Arbeitszeiten."], correctIndex: 1, explanation: "Leicht messbare Mengen können Beratung, Kooperation und Urteilsvermögen verdrängen." },
    ],
    evidence: [
      { statement: "Automatisierung kann Beschäftigte zugleich entlasten und stärker fordern.", correctAnswer: "richtig", explanation: "Routine entfällt, während Verantwortung und Kontrollaufgaben wachsen." },
      { statement: "Der Text fordert, dass alle Beschäftigten programmieren lernen.", correctAnswer: "falsch", explanation: "Ausdrücklich heißt es, dass nicht alle programmieren können müssen." },
      { statement: "In deutschen Verwaltungen ist der KI-Einsatz seit 2025 gesetzlich vorgeschrieben.", correctAnswer: "nicht_im_text", explanation: "Eine solche gesetzliche Pflicht wird nicht erwähnt." },
    ],
    vocabulary: [
      { term: "die Urteilskraft", article: "die", meaningEn: "judgement", example: "Automatische Vorschläge ersetzen keine menschliche Urteilskraft." },
      { term: "ambivalent", article: "—", meaningEn: "ambivalent; mixed", example: "Die Folgen der Automatisierung sind ambivalent." },
      { term: "die Mitbestimmung", article: "die", meaningEn: "co-determination", example: "Mitbestimmung kann die Einführung neuer Systeme begleiten." },
      { term: "verdichten", article: "—", meaningEn: "to intensify; condense", example: "Digitale Kontrolle kann die Arbeit verdichten." },
      { term: "vorbehalten", article: "—", meaningEn: "reserved for", example: "Bestimmte Entscheidungen bleiben Menschen vorbehalten." },
    ],
    vocabularyQuiz: [
      { sentence: "Bei unklaren Fällen ist weiterhin menschliche ____ erforderlich.", options: ["Urteilskraft", "Erwerbslosigkeit", "Kennzahl", "Einweisung"], correctIndex: 0, explanation: "Urteilskraft bezeichnet die Fähigkeit, begründet und situationsangemessen zu entscheiden." },
      { sentence: "Die Folgen der Technik sind ____: Sie kann entlasten, aber auch Kontrolle verstärken.", options: ["monoton", "ambivalent", "quantifizierbar", "vorbehalten"], correctIndex: 1, explanation: "Ambivalent bedeutet, dass etwas widersprüchliche Seiten hat." },
    ],
  },
  {
    id: "builtin-erinnerungskultur",
    title: "Die unbequeme Gegenwart der Vergangenheit",
    subtitle: "Warum Erinnerungskultur nicht nur bewahren, sondern immer wieder neu verhandeln muss.",
    topic: "Kultur & Erinnerung",
    level: "C1",
    estimatedMinutes: 9,
    createdAt,
    paragraphs: [
      "Denkmäler wirken, als seien sie für die Ewigkeit errichtet. Ihre Botschaften verändern sich dennoch, weil jede Generation andere Fragen an sie richtet. Eine Statue, die bei ihrer Aufstellung als Ausdruck nationalen Stolzes galt, kann später an koloniale Gewalt erinnern. Ein Straßenname, der lange kaum beachtet wurde, wird plötzlich zum Gegenstand öffentlicher Auseinandersetzung. Nicht der Stein hat sich verändert, sondern das gesellschaftliche Wissen über die Person oder das Ereignis, das er repräsentiert.",
      "In solchen Konflikten wird häufig behauptet, eine Umbenennung lösche Geschichte aus. Dieses Argument verwechselt Erinnerung mit Ehrung. Niemand fordert, belastete Persönlichkeiten aus Archiven oder Geschichtsbüchern zu entfernen. Zur Debatte steht vielmehr, wem eine Gesellschaft im Alltag symbolische Anerkennung verleiht. Ein Denkmal informiert nicht neutral. Schon seine Größe, sein Standort und die feierliche Darstellung treffen eine Auswahl und geben eine Wertung vor.",
      "Gleichwohl wäre es zu einfach, jedes problematische Monument zu beseitigen. Sichtbare Widersprüche können produktiv sein, wenn sie erklärt werden. Zusätzliche Tafeln, künstlerische Gegendenkmäler oder digitale Angebote ermöglichen es, verschiedene Perspektiven nebeneinanderzustellen. Allerdings darf Kontextualisierung nicht zu einer bequemen Formel werden. Eine kleine Texttafel am Rand kann die überwältigende Wirkung einer heroischen Statue kaum ausgleichen. Form und Zugänglichkeit der Ergänzung sind deshalb ebenso wichtig wie ihr Inhalt.",
      "Besonders deutlich zeigt sich die Frage der Zugänglichkeit in Museen. Viele Einrichtungen besitzen Objekte, die während kolonialer Herrschaft unter Gewalt, Zwang oder ungleichen Machtverhältnissen nach Europa gelangten. Die Herkunft lässt sich nicht immer lückenlos rekonstruieren. Dennoch entbindet fehlende Dokumentation Museen nicht von der Verantwortung, aktiv zu forschen und mit Herkunftsgesellschaften zusammenzuarbeiten. Rückgabe ist dabei eine Möglichkeit, aber nicht die einzige. Denkbar sind gemeinsamer Besitz, langfristige Leihgaben oder Ausstellungen, deren Deutungshoheit geteilt wird.",
      "Kritiker solcher Veränderungen fürchten, heutige moralische Maßstäbe würden unzulässig auf frühere Zeiten übertragen. Tatsächlich muss historische Forschung damalige Normen und Handlungsspielräume berücksichtigen. Doch auch in der Vergangenheit waren Unterdrückung und Enteignung keineswegs überall akzeptiert. Betroffene leisteten Widerstand, Zeitgenossen äußerten Kritik, und rechtliche Regeln wurden bewusst umgangen. Der Hinweis auf den historischen Kontext kann erklären, warum etwas geschah; er macht die Folgen nicht automatisch legitim.",
      "Erinnerungspolitik betrifft außerdem nicht nur staatliche Institutionen. Familien bewahren Fotos, erzählen bestimmte Geschichten und verschweigen andere. Stadtviertel feiern Jubiläen, Unternehmen präsentieren ihre Tradition, Vereine benennen Preise nach früheren Mitgliedern. Überall entsteht ein Bild der Vergangenheit, das Zugehörigkeit stiftet. Wer darin nicht vorkommt, erlebt Geschichte als etwas, das anderen gehört. Eine vielfältigere Erinnerung erweitert daher nicht bloß das Wissen; sie verändert auch, wer sich als Teil des gesellschaftlichen Gedächtnisses verstehen kann.",
      "Dabei ist Beteiligung anspruchsvoller, als eine öffentliche Veranstaltung anzukündigen. Häufig sprechen dort vor allem Menschen, die Zeit, Vorwissen und Vertrauen in Institutionen besitzen. Andere bleiben fern, obwohl die Entscheidung sie unmittelbar betrifft. Mehrsprachige Informationen, aufsuchende Gespräche und eine Vergütung für beratende Arbeit können den Kreis der Stimmen erweitern. Beteiligung ist jedoch nur glaubwürdig, wenn offenbleibt, welche Aspekte tatsächlich noch verändert werden können.",
      "Digitale Medien verschieben die Auseinandersetzung zusätzlich. Historische Bilder zirkulieren ohne ihren ursprünglichen Zusammenhang, kurze Beiträge belohnen eindeutige Urteile, und lokale Konflikte erreichen innerhalb weniger Stunden ein internationales Publikum. Das kann verdrängte Perspektiven sichtbar machen, erschwert aber langsame Recherche. Institutionen müssen deshalb schneller kommunizieren, ohne vorschnelle Gewissheiten zu produzieren. Gerade in emotionalen Debatten ist es legitim, vorläufige Erkenntnisse als vorläufig zu kennzeichnen.",
      "Auch das Schweigen kann Teil eines Erinnerungsortes sein. Nicht jedes Leiden lässt sich durch eine spektakuläre Form angemessen darstellen. Manche Gedenkstätten arbeiten mit Leere, Namen oder persönlichen Gegenständen, damit Besucher eigene Beziehungen zum Geschehen entwickeln. Entscheidend ist, dass Zurückhaltung nicht mit Unbestimmtheit verwechselt wird. Ein Ort darf offen wirken und dennoch präzise benennen, wer Gewalt ausübte, wer betroffen war und welche Strukturen sie ermöglichten.",
      "Eine demokratische Erinnerungskultur braucht folglich weder starre Verehrung noch permanente Säuberung. Sie braucht Verfahren, in denen historische Erkenntnisse, Erfahrungen Betroffener und heutige Wertentscheidungen sichtbar miteinander ringen. Das Ergebnis kann eine Umbenennung, eine Ergänzung oder der bewusste Erhalt eines irritierenden Ortes sein. Entscheidend ist, dass die Entscheidung begründet und überprüfbar bleibt. Gerade weil Vergangenheit nicht geändert werden kann, muss ihre öffentliche Darstellung veränderbar sein.",
    ],
    mcq: [
      { question: "Welche Unterscheidung ist für die Argumentation zentral?", options: ["Zwischen Kunst und Architektur", "Zwischen Erinnerung und öffentlicher Ehrung", "Zwischen Museen und Archiven", "Zwischen privaten und digitalen Medien"], correctIndex: 1, explanation: "Eine Person kann historisch erinnert werden, ohne weiterhin durch einen Straßennamen oder ein Denkmal geehrt zu werden." },
      { question: "Warum reicht eine Zusatztafel laut Text nicht immer aus?", options: ["Weil Tafeln grundsätzlich verboten sind.", "Weil ihre Gestaltung die starke Wirkung eines Monuments möglicherweise nicht ausgleicht.", "Weil Besucher ausschließlich digitale Informationen akzeptieren.", "Weil historische Texte nicht übersetzt werden können."], correctIndex: 1, explanation: "Kontextualisierung muss auch formal sichtbar und zugänglich sein." },
      { question: "Welche Position nimmt der Text zur Rückgabe von Museumsobjekten ein?", options: ["Sie ist immer die einzige gerechte Lösung.", "Sie soll grundsätzlich ausgeschlossen werden.", "Sie ist eine von mehreren möglichen Formen verantwortlicher Zusammenarbeit.", "Sie ist nur bei vollständig dokumentierter Herkunft erlaubt."], correctIndex: 2, explanation: "Genannt werden außerdem geteilter Besitz, Leihgaben und gemeinsame Deutung." },
    ],
    evidence: [
      { statement: "Die Bedeutung eines Denkmals kann sich ändern, obwohl das Denkmal selbst unverändert bleibt.", correctAnswer: "richtig", explanation: "Gesellschaftliches Wissen und gegenwärtige Fragen verändern seine Wahrnehmung." },
      { statement: "Fehlende Herkunftsdokumente befreien Museen von weiterer Verantwortung.", correctAnswer: "falsch", explanation: "Museen sollen gerade dann aktiv forschen und kooperieren." },
      { statement: "Die Mehrheit der Deutschen befürwortet die Umbenennung kolonial belasteter Straßen.", correctAnswer: "nicht_im_text", explanation: "Der Text nennt keine Umfragewerte." },
    ],
    vocabulary: [
      { term: "die Deutungshoheit", article: "die", meaningEn: "authority over interpretation", example: "Museen können ihre Deutungshoheit mit Herkunftsgesellschaften teilen." },
      { term: "lückenlos", article: "—", meaningEn: "complete; without gaps", example: "Die Herkunft ist nicht immer lückenlos dokumentiert." },
      { term: "entbinden", article: "—", meaningEn: "to release from an obligation", example: "Unwissen entbindet Institutionen nicht von ihrer Verantwortung." },
      { term: "starr", article: "—", meaningEn: "rigid", example: "Eine demokratische Erinnerung darf nicht starr sein." },
      { term: "ringen", article: "—", meaningEn: "to struggle; wrestle", example: "Die Beteiligten ringen um eine überzeugende Lösung." },
    ],
    vocabularyQuiz: [
      { sentence: "Die Quellen erlauben keine ____ Rekonstruktion des Vorgangs.", options: ["starre", "lückenlose", "heroische", "symbolische"], correctIndex: 1, explanation: "Lückenlos bedeutet vollständig und ohne fehlende Teile." },
      { sentence: "Das Museum wurde durch die fehlenden Akten nicht von seiner Verantwortung ____.", options: ["gerungen", "entbunden", "übertragen", "ausgeglichen"], correctIndex: 1, explanation: "Jemanden von einer Pflicht entbinden bedeutet, ihn davon zu befreien." },
    ],
  },
  {
    id: "builtin-wohnen-regionen",
    title: "Wohnraum ist mehr als eine Adresse",
    subtitle: "Warum der Ruf nach einem Umzug aufs Land die Wohnungskrise nur teilweise beantwortet.",
    topic: "Wohnen & Regionen",
    level: "C1",
    estimatedMinutes: 9,
    createdAt,
    paragraphs: [
      "Wenn in Großstädten die Mieten steigen, folgt häufig ein scheinbar naheliegender Rat: Wer sich die Stadt nicht leisten könne, solle in eine kleinere Gemeinde ziehen. Auf Landkarten wirken die Entfernungen überschaubar, Immobilienanzeigen versprechen größere Wohnungen zu niedrigeren Preisen. Doch Wohnraum ist kein isoliertes Gut. Sein tatsächlicher Wert hängt davon ab, ob Arbeitsplätze, Schulen, medizinische Versorgung, soziale Kontakte und öffentliche Verkehrsmittel erreichbar sind. Eine günstige Wohnung kann teuer werden, wenn zwei Autos nötig sind oder täglich mehrere Stunden für Wege verloren gehen.",
      "Die Konzentration auf Quadratmeterpreise verdeckt daher regionale Abhängigkeiten. Viele ländliche Räume haben in den vergangenen Jahrzehnten Einwohner verloren. Mit ihnen verschwanden Geschäfte, Arztpraxen und Busverbindungen. Gleichzeitig wurden spezialisierte Arbeitsplätze in Ballungsräumen geschaffen. Wer nun mehr Menschen für kleinere Orte gewinnen möchte, muss diese Entwicklung zumindest teilweise umkehren. Einzelne Neubaugebiete reichen nicht aus, wenn die übrige Infrastruktur weiter schrumpft.",
      "Digitale Arbeit schien während der Pandemie eine Lösung zu bieten. Wenn Beschäftigte nicht täglich ins Büro fahren, können sie theoretisch weiter entfernt wohnen. In der Praxis eignet sich jedoch nicht jede Tätigkeit für das Homeoffice, und viele Unternehmen verlangen wieder regelmäßige Anwesenheit. Außerdem setzt digitales Arbeiten eine zuverlässige Verbindung voraus, die regional noch immer unterschiedlich ausgebaut ist. Selbst bei guten technischen Bedingungen bleiben Berufe in Pflege, Handwerk, Gastronomie oder Produktion ortsgebunden.",
      "Dennoch besitzen kleinere Städte Potenziale, die in der Debatte oft unterschätzt werden. Sie verfügen teilweise über leerstehende Gebäude, kurze Verwaltungswege und eine starke lokale Zivilgesellschaft. Werden Bahnhöfe reaktiviert, Schulen gesichert und leerstehende Zentren umgenutzt, können neue Bewohnerinnen und Bewohner bestehende Strukturen stärken. Entscheidend ist, nicht nur Schlaforte für Pendler zu schaffen. Orte brauchen öffentliche Räume und Angebote, in denen Zugezogene und Alteingesessene Beziehungen entwickeln können.",
      "Auch die Großstadt bleibt auf politische Eingriffe angewiesen. Mehr Neubau kann den Druck mindern, stößt aber auf knappe Flächen, lange Genehmigungsverfahren und steigende Baukosten. Gleichzeitig gehen bezahlbare Wohnungen verloren, wenn Gebäude luxussaniert oder dauerhaft als Ferienunterkünfte genutzt werden. Wohnungspolitik muss deshalb bauen und Bestand schützen. Genossenschaften, kommunale Gesellschaften und langfristige Mietbindungen können dem Markt Wohnungen entziehen, ohne private Anbieter vollständig zu ersetzen.",
      "Ein oft übersehener Faktor ist die Wohnfläche pro Person. Ältere Menschen bleiben nach dem Auszug ihrer Kinder häufig in großen Wohnungen, weil kleinere Alternativen im eigenen Viertel fehlen. Familien wiederum finden kaum ausreichend große Wohnungen. Freiwillige Tauschbörsen, Umzugshilfen und barrierefreie Neubauten könnten vorhandenen Raum besser nutzen. Zwang wäre kontraproduktiv, denn eine Wohnung enthält Erinnerungen und soziale Beziehungen. Wer einen Wechsel erleichtern will, muss gleichwertige Alternativen anbieten.",
      "Für Auszubildende, Studierende und Menschen in befristeter Beschäftigung ist außerdem Flexibilität entscheidend. Klassische Mietverträge bieten Sicherheit, doch der Zugang scheitert oft an Einkommensnachweisen und hohen Kautionen. Möblierte Kurzzeitangebote schließen diese Lücke nur scheinbar, weil sie häufig besonders teuer sind. Kommunale Wohnheime, gemeinnützige Zwischenmiete und transparente Bürgschaftsmodelle könnten Übergänge ermöglichen, ohne eine dauerhafte Klasse von Mietern mit geringeren Rechten zu schaffen.",
      "Klimaschutz macht die Aufgabe nicht leichter, aber dringlicher. Unsanierte Gebäude verbrauchen viel Energie; umfassende Modernisierungen können jedoch Mieten erhöhen und Bewohner verdrängen. Förderprogramme sollten daher ökologische Wirkung mit sozialen Bindungen verbinden. Werden nur technische Maßnahmen bezuschusst, während die Folgekosten vollständig auf Mieter umgelegt werden, verliert Klimapolitik Akzeptanz. Eine faire Sanierung berücksichtigt Energieeinsparung, Warmmiete und den Verbleib der bisherigen Bewohnerschaft gemeinsam.",
      "Schließlich darf regionale Entwicklung nicht bedeuten, Wachstum überall zu erzwingen. Manche Gemeinden werden kleiner bleiben. Auch dort haben Menschen Anspruch auf erreichbare Versorgung. Mobile Gesundheitsdienste, flexible Busse und gemeinsam genutzte öffentliche Gebäude können Angebote sichern, ohne jede Struktur aus der Großstadt zu kopieren. Lebensqualität entsteht nicht aus Einwohnerzahlen allein, sondern aus Verlässlichkeit, Teilhabe und der Möglichkeit, den eigenen Alltag ohne unverhältnismäßigen Aufwand zu organisieren.",
      "Die Wohnungskrise lässt sich somit weder allein durch städtischen Neubau noch durch den Appell zum Wegzug lösen. Erforderlich ist eine räumliche Politik, die Wohnen, Mobilität, Daseinsvorsorge und regionale Wirtschaft gemeinsam betrachtet. Manche Menschen werden gern in kleinere Orte ziehen, wenn sie dort nicht auf wesentliche Möglichkeiten verzichten müssen. Andere sind auf die Stadt angewiesen und benötigen dort bezahlbaren Raum. Gerecht ist nicht, alle gleichmäßig zu verteilen, sondern unterschiedliche Lebensentwürfe praktisch möglich zu machen.",
    ],
    mcq: [
      { question: "Warum kritisiert der Text den einfachen Rat zum Umzug aufs Land?", options: ["Weil Wohnungen auf dem Land immer teurer sind.", "Weil Wohnkosten ohne Erreichbarkeit und Infrastruktur unvollständig betrachtet werden.", "Weil ländliche Gemeinden keine neuen Einwohner aufnehmen dürfen.", "Weil Homeoffice in Deutschland verboten ist."], correctIndex: 1, explanation: "Der Text betrachtet Mobilität, Versorgung, Arbeit und soziale Beziehungen als Teil des Wohnwerts." },
      { question: "Was sollte bei der Entwicklung kleinerer Städte vermieden werden?", options: ["Die Reaktivierung alter Bahnhöfe", "Die Nutzung leerstehender Gebäude", "Die Schaffung reiner Schlaforte ohne soziales Leben", "Die Sicherung von Schulen"], correctIndex: 2, explanation: "Neue Wohngebiete allein schaffen noch keine lebendigen Orte." },
      { question: "Wie könnte vorhandener Wohnraum besser genutzt werden?", options: ["Durch verpflichtende Räumung großer Wohnungen", "Durch Tauschbörsen, Umzugshilfen und passende kleinere Wohnungen", "Durch die Umwandlung aller Wohnungen in Ferienunterkünfte", "Durch den Abbau barrierefreier Wohnungen"], correctIndex: 1, explanation: "Freiwilliger Wechsel braucht attraktive und gleichwertige Alternativen." },
    ],
    evidence: [
      { statement: "Eine niedrige Miete kann durch hohe Mobilitätskosten relativiert werden.", correctAnswer: "richtig", explanation: "Zwei Autos oder lange Wege können die Ersparnis aufzehren." },
      { statement: "Nach Darstellung des Textes kann jede berufliche Tätigkeit im Homeoffice ausgeübt werden.", correctAnswer: "falsch", explanation: "Mehrere ortsgebundene Berufsfelder werden ausdrücklich genannt." },
      { statement: "Kommunale Wohnungsunternehmen besitzen bundesweit mehr Wohnungen als private Anbieter.", correctAnswer: "nicht_im_text", explanation: "Der Text enthält keinen solchen Zahlenvergleich." },
    ],
    vocabulary: [
      { term: "die Daseinsvorsorge", article: "die", meaningEn: "public services of general interest", example: "Zur Daseinsvorsorge gehören etwa Verkehr und medizinische Versorgung." },
      { term: "ortsgebunden", article: "—", meaningEn: "tied to a location", example: "Pflegearbeit ist weitgehend ortsgebunden." },
      { term: "die Mietbindung", article: "die", meaningEn: "rent-control commitment", example: "Nach Ablauf der Mietbindung kann die Miete steigen." },
      { term: "Alteingesessene", article: "die", meaningEn: "long-established residents", example: "Zugezogene und Alteingesessene nutzen den neuen Treffpunkt." },
      { term: "kontraproduktiv", article: "—", meaningEn: "counterproductive", example: "Zwang wäre bei einem Wohnungstausch kontraproduktiv." },
    ],
    vocabularyQuiz: [
      { sentence: "Viele Tätigkeiten in Pflege und Handwerk bleiben ____.", options: ["barrierefrei", "ortsgebunden", "gleichwertig", "überschaubar"], correctIndex: 1, explanation: "Ortsgebunden heißt, dass die Arbeit an einem bestimmten Ort stattfinden muss." },
      { sentence: "Ein erzwungener Umzug könnte sich als ____ erweisen.", options: ["kontraproduktiv", "lückenlos", "langfristig", "kommunal"], correctIndex: 0, explanation: "Kontraproduktiv ist eine Maßnahme, die dem eigenen Ziel entgegenwirkt." },
    ],
  },
  {
    id: "builtin-mehrsprachigkeit",
    title: "Mehr als eine Sprache im Kopf",
    subtitle: "Warum sprachliches Mischen keine Schwäche, sondern oft eine präzise soziale Fähigkeit ist.",
    topic: "Sprache & Identität",
    level: "C1",
    estimatedMinutes: 3,
    createdAt,
    paragraphs: [
      "Mehrsprachige Menschen wechseln im Gespräch häufig zwischen Sprachen. Außenstehende deuten dieses sogenannte Code-Switching manchmal als Zeichen mangelnder Sprachkenntnisse. Sprachwissenschaftliche Beobachtungen zeigen jedoch, dass der Wechsel meist Regeln folgt. Eine Sprache kann Nähe ausdrücken, eine andere fachliche Genauigkeit oder Distanz. Mitunter existiert für eine Erfahrung auch nur in einer Sprache der passende Ausdruck.",
      "Welche Sprache gewählt wird, hängt vom Gegenüber, vom Ort und vom Thema ab. Geschwister sprechen zu Hause vielleicht anders miteinander als in der Universität. Ein einzelnes Wort kann Zugehörigkeit markieren oder eine gemeinsame Erinnerung aufrufen. Gerade diese Anpassung setzt ein feines Gespür für soziale Situationen voraus.",
      "Problematisch wird Mehrsprachigkeit erst, wenn Institutionen sie ausschließlich als Defizit behandeln. Kinder brauchen selbstverständlich sichere Kenntnisse der Unterrichtssprache. Das gelingt aber nicht besser, indem ihre Familiensprachen abgewertet werden. Werden vorhandene Kenntnisse einbezogen, können Lernende Begriffe vergleichen und sprachliche Strukturen bewusster erkennen. Ziel ist deshalb nicht ein beliebiges Mischen, sondern ein Repertoire, aus dem Menschen situationsgerecht wählen können.",
      "Auch Erwachsene erleben, dass ihre Sprachen unterschiedlich bewertet werden. Englisch gilt im Beruf oft als Qualifikation, während andere Sprachen unsichtbar bleiben oder nur bei Problemen erwartet werden. Eine gerechte Anerkennung müsste nicht jede Sprache gleich verwenden, aber die tatsächlichen Kompetenzen benennen: vermitteln, übersetzen, kulturelle Bedeutungen erklären und zwischen verschiedenen Kommunikationsstilen wechseln.",
    ],
    mcq: [
      { question: "Wie bewertet der Text Code-Switching?", options: ["Als grundsätzliches Sprachdefizit", "Als häufig regelgeleitete soziale Fähigkeit", "Als Hindernis für jede Form des Lernens", "Als ausschließlich private Gewohnheit"], correctIndex: 1, explanation: "Der Sprachwechsel wird als situationsabhängig und funktional beschrieben." },
      { question: "Was empfiehlt der Text Bildungseinrichtungen?", options: ["Familiensprachen zu verbieten", "Nur Grammatik zu unterrichten", "Vorhandene Sprachen als Lernressource einzubeziehen", "Auf eine Unterrichtssprache zu verzichten"], correctIndex: 2, explanation: "Vergleiche zwischen Sprachen können das Sprachbewusstsein fördern." },
    ],
    evidence: [
      { statement: "Die Sprachwahl kann soziale Nähe oder Distanz ausdrücken.", correctAnswer: "richtig", explanation: "Diese Funktionen werden im ersten Absatz genannt." },
      { statement: "Der Text nennt eine konkrete Zahl mehrsprachiger Kinder in Deutschland.", correctAnswer: "nicht_im_text", explanation: "Es werden keine statistischen Zahlen angegeben." },
    ],
    vocabulary: [
      { term: "das Repertoire", article: "das", meaningEn: "repertoire; range", example: "Mehrsprachige verfügen über ein vielfältiges sprachliches Repertoire." },
      { term: "abwerten", article: "—", meaningEn: "to devalue", example: "Familiensprachen sollten nicht abgewertet werden." },
      { term: "situationsgerecht", article: "—", meaningEn: "appropriate to the situation", example: "Sie wählt ihre Ausdrucksweise situationsgerecht." },
    ],
    vocabularyQuiz: [
      { sentence: "Gute Kommunikation setzt voraus, dass man ____ aus seinem sprachlichen Repertoire wählt.", options: ["mangelhaft", "situationsgerecht", "ausschließlich", "beliebig"], correctIndex: 1, explanation: "Situationsgerecht bedeutet passend zu Kontext und Gegenüber." },
    ],
  },
  {
    id: "builtin-reparieren",
    title: "Das zweite Leben der Dinge",
    subtitle: "Weshalb Reparieren nicht allein eine Frage persönlicher Disziplin ist.",
    topic: "Konsum & Nachhaltigkeit",
    level: "C1",
    estimatedMinutes: 3,
    createdAt,
    paragraphs: [
      "Viele Menschen würden ein defektes Gerät gern reparieren lassen. Trotzdem entscheiden sie sich häufig für einen Neukauf. Der Grund ist nicht zwangsläufig Bequemlichkeit: Ersatzteile fehlen, Gehäuse lassen sich nicht öffnen oder die Reparatur kostet fast so viel wie ein neues Produkt. Nachhaltiger Konsum hängt daher auch davon ab, wie Dinge konstruiert und verkauft werden.",
      "Ein gesetzliches Recht auf Reparatur soll Hersteller verpflichten, Ersatzteile und Informationen länger bereitzustellen. Befürworter erwarten weniger Elektroschrott und neue Aufträge für lokale Werkstätten. Kritiker warnen, umfangreiche Lagerhaltung könne Produkte verteuern. Außerdem braucht eine fachgerechte Reparatur Qualifikation; frei zugängliche Anleitungen allein lösen nicht jedes Problem.",
      "Repair-Cafés zeigen dennoch, dass Reparieren mehr sein kann als Schadensbehebung. Menschen teilen Wissen, verlieren die Scheu vor Technik und entwickeln eine andere Beziehung zu Gegenständen. Solche Initiativen können industrielle Regeln nicht ersetzen. Sie machen aber sichtbar, dass die kurze Lebensdauer vieler Produkte weder naturgegeben noch alternativlos ist.",
      "Entscheidend ist außerdem der Preisvergleich. Neue Geräte erscheinen günstig, weil Rohstoffabbau, Umweltfolgen und spätere Entsorgung nur teilweise im Verkaufspreis stecken. Reparaturen enthalten dagegen sichtbar menschliche Arbeitszeit. Werden beide Optionen nach unterschiedlichen Maßstäben berechnet, wirkt Wegwerfen wirtschaftlicher, als es gesellschaftlich tatsächlich ist. Längere Garantien und besser reparierbare Konstruktionen könnten dieses Verhältnis verschieben.",
    ],
    mcq: [
      { question: "Welche Hauptaussage entwickelt der Text?", options: ["Verbraucher sind allein für Elektroschrott verantwortlich.", "Reparaturfähigkeit hängt auch von Produktgestaltung und Rahmenbedingungen ab.", "Repair-Cafés sollen professionelle Werkstätten verbieten.", "Ersatzteile sollten grundsätzlich kostenlos sein."], correctIndex: 1, explanation: "Individuelle Absicht reicht nicht, wenn Konstruktion, Preis und Teileverfügbarkeit entgegenstehen." },
      { question: "Welchen zusätzlichen Nutzen haben Repair-Cafés?", options: ["Sie ersetzen sämtliche gesetzlichen Regeln.", "Sie fördern Wissen und einen anderen Umgang mit Dingen.", "Sie verkaufen vor allem neue Geräte.", "Sie garantieren jede Reparatur."], correctIndex: 1, explanation: "Der Text nennt Wissensaustausch, technische Sicherheit und eine veränderte Beziehung zu Gegenständen." },
    ],
    evidence: [
      { statement: "Eine Reparatur kann wirtschaftlich kaum günstiger als ein Neukauf sein.", correctAnswer: "richtig", explanation: "Dies wird als ein Grund für den Neukauf genannt." },
      { statement: "Alle Hersteller bieten bereits zehn Jahre lang Ersatzteile an.", correctAnswer: "nicht_im_text", explanation: "Eine solche bestehende Praxis oder Frist wird nicht genannt." },
    ],
    vocabulary: [
      { term: "die Schadensbehebung", article: "die", meaningEn: "repair; remedying damage", example: "Das Treffen dient nicht nur der Schadensbehebung." },
      { term: "naturgegeben", article: "—", meaningEn: "natural; inevitable", example: "Kurze Produktzyklen sind nicht naturgegeben." },
      { term: "die Lagerhaltung", article: "die", meaningEn: "stockholding; inventory", example: "Eine lange Lagerhaltung verursacht Kosten." },
    ],
    vocabularyQuiz: [
      { sentence: "Die kurze Lebensdauer vieler Geräte ist keineswegs ____.", options: ["fachgerecht", "naturgegeben", "umfangreich", "zugänglich"], correctIndex: 1, explanation: "Naturgegeben bedeutet von Natur aus vorhanden und kaum veränderbar." },
    ],
  },
  {
    id: "builtin-schlaf",
    title: "Müde in einer wachen Gesellschaft",
    subtitle: "Warum Schlafprobleme nicht immer mit besserer Selbstdisziplin verschwinden.",
    topic: "Gesundheit & Alltag",
    level: "C1",
    estimatedMinutes: 3,
    createdAt,
    paragraphs: [
      "Ratgeber behandeln guten Schlaf gern als optimierbares Projekt: kein Bildschirm am Abend, regelmäßige Zeiten, ausreichend Bewegung. Solche Empfehlungen können helfen. Sie erzeugen jedoch leicht den Eindruck, Müdigkeit sei vor allem persönliches Versagen. Dabei beeinflussen Schichtarbeit, Lärm, Sorgearbeit und finanzielle Unsicherheit, wann und wie lange Menschen schlafen können.",
      "Hinzu kommt ein Widerspruch moderner Arbeitskultur. Einerseits gilt Erholung als Voraussetzung von Leistung. Andererseits wird ständige Erreichbarkeit häufig als Engagement interpretiert. Wer spät antwortet, wirkt pflichtbewusst; wer Grenzen setzt, muss sie begründen. Schlaf wird so zur privaten Reparaturzeit für Belastungen, die gesellschaftlich produziert werden.",
      "Eine sinnvolle Schlafpolitik würde individuelle Gewohnheiten nicht für bedeutungslos erklären. Sie würde sie aber um strukturelle Maßnahmen ergänzen: verlässlichere Dienstpläne, Schutz vor nächtlichem Lärm und Arbeitskulturen, in denen Nichterreichbarkeit akzeptiert ist. Nicht jede schlaflose Nacht ist politisch. Doch eine Gesellschaft sollte prüfen, warum bestimmte Gruppen systematisch weniger Erholung erhalten als andere.",
      "Auch die medizinische Versorgung muss differenzieren. Kurzfristige Schlafprobleme gehören zum Leben; anhaltende Beschwerden können dagegen behandlungsbedürftig sein. Wer Betroffenen lediglich eine perfekte Abendroutine empfiehlt, übersieht möglicherweise körperliche oder psychische Ursachen. Hilfreich ist eine Beratung, die Lebensumstände ernst nimmt, ohne jede Müdigkeit sofort zur Krankheit zu erklären. Dabei sollte Hilfe früh erreichbar sein und nicht erst nach monatelanger Erschöpfung beginnen.",
    ],
    mcq: [
      { question: "Was kritisiert der Text an üblichen Schlafratschlägen?", options: ["Sie sind medizinisch immer falsch.", "Sie können strukturelle Ursachen als persönliches Problem erscheinen lassen.", "Sie empfehlen zu viel Schichtarbeit.", "Sie lehnen Bewegung grundsätzlich ab."], correctIndex: 1, explanation: "Die individuelle Perspektive verdeckt mitunter Arbeitszeiten, Lärm und Unsicherheit." },
      { question: "Was wäre Teil einer strukturellen Lösung?", options: ["Mehr nächtliche Nachrichten", "Unvorhersehbare Dienstpläne", "Akzeptierte Nichterreichbarkeit", "Weniger Lärmschutz"], correctIndex: 2, explanation: "Grenzen der Erreichbarkeit werden ausdrücklich als Maßnahme genannt." },
    ],
    evidence: [
      { statement: "Der Text hält persönliche Schlafgewohnheiten für völlig bedeutungslos.", correctAnswer: "falsch", explanation: "Sie bleiben wichtig, sollen aber durch strukturelle Maßnahmen ergänzt werden." },
      { statement: "Finanzielle Unsicherheit kann den Schlaf beeinflussen.", correctAnswer: "richtig", explanation: "Sie wird im ersten Absatz ausdrücklich aufgeführt." },
    ],
    vocabulary: [
      { term: "die Erreichbarkeit", article: "die", meaningEn: "availability; reachability", example: "Ständige Erreichbarkeit kann die Erholung beeinträchtigen." },
      { term: "verlässlich", article: "—", meaningEn: "reliable; predictable", example: "Beschäftigte brauchen verlässliche Dienstpläne." },
      { term: "systematisch", article: "—", meaningEn: "systematically", example: "Manche Gruppen sind systematisch stärker belastet." },
    ],
    vocabularyQuiz: [
      { sentence: "Planbare Erholung setzt ____ Arbeitszeiten voraus.", options: ["systematische", "private", "verlässliche", "schlaflose"], correctIndex: 2, explanation: "Verlässlich bedeutet zuverlässig und vorhersehbar." },
    ],
  },
  {
    id: "builtin-ehrenamt",
    title: "Engagement braucht Grenzen",
    subtitle: "Warum freiwillige Arbeit unverzichtbar ist, aber staatliche Aufgaben nicht dauerhaft ersetzen darf.",
    topic: "Gesellschaft & Ehrenamt",
    level: "C1",
    estimatedMinutes: 3,
    createdAt,
    paragraphs: [
      "Ohne freiwilliges Engagement würden Sportvereine, Nachbarschaftshilfen und Kulturprojekte vielerorts kaum funktionieren. Ehrenamtliche kennen lokale Bedürfnisse, reagieren flexibel und schaffen Beziehungen, die eine Behörde nicht anordnen kann. Gerade in Krisen zeigt sich diese Stärke besonders deutlich.",
      "Doch Anerkennung kann in Ausnutzung umschlagen. Wenn Kommunen soziale Angebote kürzen und selbstverständlich erwarten, dass Freiwillige einspringen, wird aus Engagement unbezahlter Ersatz für reguläre Arbeit. Das trifft nicht alle gleichermaßen: Wer wenig Zeit oder Geld hat, kann sich ein dauerhaftes Ehrenamt schwerer leisten. Eine Gesellschaft, die Beteiligung fordert, muss deshalb auch Zugänge schaffen.",
      "Dazu gehören Räume, Versicherung, Fahrtkostenerstattung und hauptamtliche Koordination. Solche Unterstützung widerspricht dem freiwilligen Charakter nicht, sondern schützt ihn. Ehrenamt ist besonders wertvoll, wenn Menschen zusätzliche Ideen verwirklichen können. Es verliert seine Freiheit, sobald grundlegende Versorgung von ihrer ständigen Verfügbarkeit abhängt.",
      "Anerkennung sollte sich deshalb nicht auf Urkunden und Dankesreden beschränken. Freiwillige brauchen Mitsprache darüber, welche Aufgaben sinnvoll sind und wann sie Unterstützung benötigen. Ebenso wichtig ist das Recht, eine Tätigkeit ohne Schuldgefühl zu beenden. Nur wenn Engagement zeitlich begrenzt, veränderbar und wirklich freiwillig bleibt, kann es langfristig Vertrauen statt Überforderung erzeugen. Regelmäßige Pausen und klar verteilte Verantwortung verhindern zudem, dass wenige besonders Engagierte dauerhaft die gesamte Arbeit tragen und schließlich ausbrennen.",
    ],
    mcq: [
      { question: "Wo zieht der Text eine Grenze des Ehrenamts?", options: ["Bei jeder Zusammenarbeit mit Behörden", "Wenn es dauerhaft reguläre Arbeit und Grundversorgung ersetzen soll", "Bei der Erstattung von Fahrtkosten", "Sobald lokale Beziehungen entstehen"], correctIndex: 1, explanation: "Freiwillige sollen zusätzliche Möglichkeiten schaffen, nicht gekürzte Regelstrukturen kompensieren." },
      { question: "Warum sind Zugänge zum Ehrenamt ungleich?", options: ["Weil Engagement gesetzlich nur Wohlhabenden erlaubt ist.", "Weil verfügbare Zeit und finanzielle Mittel unterschiedlich verteilt sind.", "Weil Vereine keine neuen Mitglieder aufnehmen.", "Weil Fahrtkosten nie erstattet werden dürfen."], correctIndex: 1, explanation: "Zeit und Geld beeinflussen, wer dauerhaft unbezahlte Aufgaben übernehmen kann." },
    ],
    evidence: [
      { statement: "Hauptamtliche Koordination kann freiwilliges Engagement unterstützen.", correctAnswer: "richtig", explanation: "Sie wird als sinnvolle Infrastruktur genannt." },
      { statement: "Der Text fordert die Abschaffung kommunaler Kulturprojekte.", correctAnswer: "falsch", explanation: "Er warnt vielmehr davor, öffentliche Aufgaben auf Freiwillige abzuwälzen." },
    ],
    vocabulary: [
      { term: "einspringen", article: "—", meaningEn: "to step in", example: "Freiwillige springen kurzfristig ein." },
      { term: "die Fahrtkostenerstattung", article: "die", meaningEn: "travel expense reimbursement", example: "Eine Fahrtkostenerstattung erleichtert die Teilnahme." },
      { term: "abwälzen", article: "—", meaningEn: "to shift a burden onto others", example: "Der Staat darf seine Verantwortung nicht auf Ehrenamtliche abwälzen." },
    ],
    vocabularyQuiz: [
      { sentence: "Öffentliche Stellen dürfen ihre Verantwortung nicht dauerhaft auf Freiwillige ____.", options: ["einspringen", "anordnen", "abwälzen", "erstatten"], correctIndex: 2, explanation: "Eine Verantwortung abwälzen heißt, sie unangemessen anderen aufzubürden." },
    ],
  },
  {
    id: "builtin-bibliotheken",
    title: "Die Bibliothek als öffentlicher Raum",
    subtitle: "Weshalb Bibliotheken im digitalen Zeitalter nicht verschwinden, sondern neue Aufgaben übernehmen.",
    topic: "Bildung & Öffentlichkeit",
    level: "C1",
    estimatedMinutes: 3,
    createdAt,
    paragraphs: [
      "Weil Informationen jederzeit online verfügbar sind, erscheinen Bibliotheken manchen wie Einrichtungen aus einer vergangenen Epoche. Diese Sicht reduziert sie auf Bücherlager. Moderne Bibliotheken bieten jedoch etwas, das im Netz knapp ist: einen nichtkommerziellen Raum, in dem Menschen sich aufhalten können, ohne etwas kaufen zu müssen.",
      "Dort lernen Schülerinnen neben Rentnern, Arbeitssuchende nutzen Computer, und neu Zugewanderte finden Sprachmaterialien. Mitarbeitende helfen nicht nur bei der Suche nach Büchern, sondern auch dabei, Quellen einzuschätzen und digitale Anträge zu verstehen. Gerade weil staatliche und private Angebote ins Internet verlagert werden, wächst der Bedarf an solcher Unterstützung.",
      "Damit erweitert sich der Auftrag der Bibliothek. Diese Entwicklung birgt Konflikte, denn ruhiges Lesen, Veranstaltungen und soziale Beratung benötigen unterschiedliche Bedingungen. Erfolgreiche Häuser trennen daher Zonen, statt eine Nutzung gegen die andere auszuspielen. Ihre Zukunft liegt nicht in der Entscheidung zwischen Buch und Begegnung, sondern in einer klugen Verbindung beider Funktionen.",
      "Dafür benötigen Bibliotheken ausreichend Personal. Offene Türen allein schaffen noch keinen zugänglichen Ort, wenn niemand bei Recherche, Technik oder Konflikten helfen kann. Investitionen in Gebäude und digitale Angebote sollten deshalb nicht gegen fachkundige Beratung ausgespielt werden. Die Qualität des Raums entsteht durch seine Ausstattung und durch die Menschen, die ihn verlässlich betreuen.",
    ],
    mcq: [
      { question: "Welchen besonderen Wert schreibt der Text Bibliotheken zu?", options: ["Sie verkaufen Bücher günstiger als das Internet.", "Sie bieten einen nichtkommerziellen zugänglichen Raum.", "Sie ersetzen alle Sozialbehörden.", "Sie sind ausschließlich ruhige Lesesäle."], correctIndex: 1, explanation: "Aufenthalt ohne Konsumzwang wird als knappe öffentliche Ressource beschrieben." },
      { question: "Wie können unterschiedliche Nutzungen miteinander vereinbart werden?", options: ["Durch räumlich getrennte Zonen", "Durch ein Verbot von Veranstaltungen", "Durch die Abschaffung gedruckter Bücher", "Durch kostenpflichtigen Eintritt"], correctIndex: 0, explanation: "Der Text nennt eine räumliche Differenzierung statt gegenseitiger Verdrängung." },
    ],
    evidence: [
      { statement: "Die Digitalisierung kann den Beratungsbedarf in Bibliotheken erhöhen.", correctAnswer: "richtig", explanation: "Digitale Anträge und Quellenbewertung schaffen neue Unterstützungsaufgaben." },
      { statement: "Alle deutschen Bibliotheken sind rund um die Uhr geöffnet.", correctAnswer: "nicht_im_text", explanation: "Öffnungszeiten werden nicht behandelt." },
    ],
    vocabulary: [
      { term: "der Konsumzwang", article: "der", meaningEn: "pressure to consume", example: "In der Bibliothek besteht kein Konsumzwang." },
      { term: "ausspielen", article: "—", meaningEn: "to play off against", example: "Man sollte verschiedene Nutzergruppen nicht gegeneinander ausspielen." },
      { term: "der Auftrag", article: "der", meaningEn: "mission; mandate", example: "Der öffentliche Auftrag der Bibliothek erweitert sich." },
    ],
    vocabularyQuiz: [
      { sentence: "Lesen und Begegnung müssen nicht gegeneinander ____ werden.", options: ["eingeschätzt", "verlagert", "ausgespielt", "reduziert"], correctIndex: 2, explanation: "Etwas gegeneinander ausspielen bedeutet, einen künstlichen Gegensatz zwischen beiden herzustellen." },
    ],
  },
];
